<?php
// ============================================================
// GEMB Access Control — application_doc.php
// The ONLY route to uploaded application documents (IDs,
// police clearances, payment proofs). Files live outside the
// webroot with random hex names and no extension.
// Guard: requireSecurity() — identical to security.php actions.
// ============================================================
require_once __DIR__ . '/application_lib.php';
if (session_status() === PHP_SESSION_NONE) session_start();

// Documents are viewed by the site manager (contractor verification)
// AND by admin (pet/tenant/to-let/estate agent approvals).
if (empty($_SESSION['security_id']) && empty($_SESSION['admin_id'])) {
    http_response_code(403);
    exit('Access denied.');
}

$docId = filter_var($_GET['id'] ?? 0, FILTER_VALIDATE_INT);
if (!$docId) { http_response_code(404); exit('Document not found.'); }

$stmt = db()->prepare(
    "SELECT stored_name, orig_filename, mime_type, file_size
     FROM application_documents WHERE id=? LIMIT 1"
);
$stmt->execute([$docId]);
$doc = $stmt->fetch();
if (!$doc) { http_response_code(404); exit('Document not found.'); }

// stored_name is generated by us as 64-char hex; re-validate defensively
if (!preg_match('/^[a-f0-9]{64}$/', $doc['stored_name'])) { http_response_code(500); exit('Invalid record.'); }

$path = APP_UPLOAD_DIR . '/' . $doc['stored_name'];
if (!is_file($path)) { http_response_code(404); exit('File missing from storage.'); }

$safeName = preg_replace('/[^A-Za-z0-9._ -]/', '_', $doc['orig_filename']);

header('Content-Type: ' . $doc['mime_type']);
header('Content-Length: ' . $doc['file_size']);
header('Content-Disposition: inline; filename="' . $safeName . '"');
header('X-Content-Type-Options: nosniff');
header('Content-Security-Policy: sandbox');   // neuter any scripts embedded in PDFs
header('Cache-Control: private, no-store');
readfile($path);
