<?php
/**
 * gemB - Secure document download proxy.
 * Documents are stored outside the webroot with random names and no
 * extension; this proxy is the ONLY way to retrieve them, and it is
 * restricted to authenticated site-manager sessions.
 */
declare(strict_types=1);
require_once __DIR__ . '/application_lib.php';

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_set_cookie_params(['httponly' => true, 'secure' => true, 'samesite' => 'Strict']);
    session_start();
}
if (empty($_SESSION['security_user_id']) || ($_SESSION['security_role'] ?? '') !== 'site_manager') {
    http_response_code(403);
    exit('Access denied.');
}

$docId = (int)($_GET['id'] ?? 0);
$stmt = $conn->prepare("SELECT stored_name, orig_filename, mime_type, file_size FROM application_documents WHERE id = ?");
$stmt->bind_param('i', $docId);
$stmt->execute();
$doc = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$doc) { http_response_code(404); exit('Document not found.'); }

// stored_name is generated by us as hex; re-validate to be safe against tampered rows
if (!preg_match('/^[a-f0-9]{64}$/', $doc['stored_name'])) { http_response_code(500); exit('Invalid record.'); }

$path = APP_UPLOAD_DIR . '/' . $doc['stored_name'];
if (!is_file($path)) { http_response_code(404); exit('File missing from storage.'); }

$safeName = preg_replace('/[^A-Za-z0-9._ -]/', '_', $doc['orig_filename']);

header('Content-Type: ' . $doc['mime_type']);
header('Content-Length: ' . $doc['file_size']);
header('Content-Disposition: inline; filename="' . $safeName . '"');
header('X-Content-Type-Options: nosniff');
header('Content-Security-Policy: sandbox');   // neuter any embedded scripts in PDFs
header('Cache-Control: private, no-store');
readfile($path);
